# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_photopage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopage',
            name='publication_date',
        ),
    ]
